### ISSUE TITLE
Can't install the rando

### ISSUE THREAD

**Issue by ooiale** [junglechief87/Seiren-Shuffle-An-Ys-8-Randomizer-#6]
So, I installed the ZIP folder, and extracted the folder with all files into the Ys 8 root folder
then I copied the script and the .exe files to the root folder. (I also had to copy the shared folder so that the .exe could load the rando logo). 
but on the rando settings interface, upon clicking on the Patch Folder, the interface stops responding for some long time (not sure if its intended or not) and upon clicking to generate a seed, the program stops responding indefinitely (at least longer than 30 minutes).
The spoiler log file is generated (it stays at size: 0 for a long time, maybe the file is not closed too?) but I assume a bunch of files are missing/wrong since upon launch, the cutscenes to progress the game are not there and there are no NPCS in the ship. (Don't remember if the first progression is made by entering the captain's room or by talking to him)

**Comment by junglechief87** [comment]
Hey there. Are you still having issues with the install? Which folder was the executable placed under?

**Comment by ooiale** [comment]
Yes, I placed the executable in the Ys 8 folder (steam/steamapps/common/ys8)
edit: its working now. uhh not sure what I did different this time but thank you!
